// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace InventoryApp.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart10(ModelBuilder modelBuilder)
        {
            // ERP-N1.8.C — persistencia normalizada de reservas de inventario.
            modelBuilder.Entity<InventoryApp.Domain.Entities.ReservaInventario>(b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int?>("ActivadaPorUsuarioId").HasColumnType("int");
                b.Property<int?>("CanceladaPorUsuarioId").HasColumnType("int");
                b.Property<int?>("ConsumidaPorUsuarioId").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<InventoryApp.Domain.Enums.EstadoReservaInventario>("Estado").HasColumnType("int");
                b.Property<int?>("ExpiradaPorUsuarioId").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaActivacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaCancelacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaConsumo").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaExpiracion").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaExpiracionAplicada").HasColumnType("datetime(6)");
                b.Property<DateTime?>("FechaLiberacion").HasColumnType("datetime(6)");
                b.Property<int?>("LiberadaPorUsuarioId").HasColumnType("int");
                b.Property<string>("MotivoCancelacion").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("MotivoLiberacion").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("Numero").IsRequired().HasMaxLength(40).HasColumnType("varchar(40)");
                b.Property<int?>("PedidoVentaId").HasColumnType("int");
                b.Property<int?>("VentaId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("Estado", "FechaExpiracion").HasDatabaseName("IX_ReservasInventario_Estado_Expiracion");
                b.HasIndex("Numero").IsUnique().HasDatabaseName("UX_ReservasInventario_Numero");
                b.HasIndex("PedidoVentaId").IsUnique().HasDatabaseName("UX_ReservasInventario_PedidoVentaId");
                b.HasIndex("VentaId").HasDatabaseName("IX_ReservasInventario_VentaId");
                b.ToTable("ReservasInventario");
            });

            modelBuilder.Entity<InventoryApp.Domain.Entities.ReservaInventarioDetalle>(b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ActualizadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("ActualizadoPorUsuarioId").HasColumnType("int");
                b.Property<int>("AlmacenId").HasColumnType("int");
                b.Property<int>("CantidadConsumida").HasColumnType("int").HasDefaultValue(0);
                b.Property<int>("CantidadReservada").HasColumnType("int");
                b.Property<string>("CreadoPorNombreUsuario").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<int?>("CreadoPorUsuarioId").HasColumnType("int");
                b.Property<DateTime>("FechaActualizacion").HasColumnType("datetime(6)");
                b.Property<DateTime>("FechaCreacion").HasColumnType("datetime(6)");
                b.Property<string>("ProductoColorSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("ProductoMarcaSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoModeloSnapshot").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("ProductoSkuSnapshot").HasMaxLength(120).HasColumnType("varchar(120)");
                b.Property<string>("ProductoTallaSnapshot").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("ProductoVarianteId").HasColumnType("int");
                b.Property<int>("ReservaInventarioId").HasColumnType("int");
                b.Property<int?>("UbicacionAlmacenId").HasColumnType("int");
                b.Property<int>("UbicacionNormalizada").ValueGeneratedOnAddOrUpdate().HasColumnType("int")
                    .HasComputedColumnSql("COALESCE(`UbicacionAlmacenId`, 0)", true);

                b.HasKey("Id");
                b.HasIndex("AlmacenId", "UbicacionAlmacenId");
                b.HasIndex("ProductoVarianteId", "AlmacenId", "UbicacionAlmacenId")
                    .HasDatabaseName("IX_ReservaDetalles_ExistenciaFisica");
                b.HasIndex("ReservaInventarioId");
                b.HasIndex("ReservaInventarioId", "ProductoVarianteId", "AlmacenId", "UbicacionNormalizada")
                    .IsUnique().HasDatabaseName("UX_ReservaDetalles_ClaveFisica");
                b.ToTable("ReservaInventarioDetalles");
            });

            modelBuilder.Entity<InventoryApp.Domain.Entities.ReservaInventario>(b =>
            {
                b.HasOne(typeof(InventoryApp.Domain.Entities.PedidoVenta), "PedidoVenta").WithMany().HasForeignKey("PedidoVentaId")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_ReservasInventario_PedidosVenta_PedidoVentaId");
                b.HasOne("InventoryApp.Domain.Entities.Venta", "Venta").WithMany().HasForeignKey("VentaId")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_ReservasInventario_Ventas_VentaId");
                b.Navigation("PedidoVenta");
                b.Navigation("Venta");
            });

            modelBuilder.Entity<InventoryApp.Domain.Entities.ReservaInventarioDetalle>(b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.Almacen", "Almacen").WithMany().HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired().HasConstraintName("FK_ReservaDetalles_Almacenes_AlmacenId");
                b.HasOne("InventoryApp.Domain.Entities.ProductoVariante", "ProductoVariante").WithMany().HasForeignKey("ProductoVarianteId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired().HasConstraintName("FK_ReservaDetalles_ProductoVariantes_ProductoVarianteId");
                b.HasOne("InventoryApp.Domain.Entities.ReservaInventario", "ReservaInventario").WithMany("Detalles").HasForeignKey("ReservaInventarioId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired().HasConstraintName("FK_ReservaInventarioDetalles_ReservasInventario_ReservaInventarioId");
                b.HasOne("InventoryApp.Domain.Entities.UbicacionAlmacen", "UbicacionAlmacen").WithMany()
                    .HasForeignKey("AlmacenId", "UbicacionAlmacenId").HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict).HasConstraintName("FK_ReservaDetalles_Ubicacion_MismoAlmacen");
                b.Navigation("Almacen");
                b.Navigation("ProductoVariante");
                b.Navigation("ReservaInventario");
                b.Navigation("UbicacionAlmacen");
            });

            modelBuilder.Entity<InventoryApp.Domain.Entities.ReservaInventario>(b =>
            {
                b.Navigation("Detalles");
            });
        }
    }
}
