// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace InventoryApp.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart4(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity("InventoryApp.Domain.Entities.ExistenciaVariante", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<int>("AlmacenId")
                    .HasColumnType("int");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<int>("ProductoVarianteId")
                    .HasColumnType("int");

                b.Property<int>("StockDisponible")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("int")
                    .HasComputedColumnSql("StockFisico - StockReservado", true);

                b.Property<int>("StockFisico")
                    .HasColumnType("int");

                b.Property<int?>("StockMaximo")
                    .HasColumnType("int");

                b.Property<int>("StockMinimo")
                    .HasColumnType("int");

                b.Property<int>("StockReservado")
                    .HasColumnType("int");

                b.Property<int>("StockTransito")
                    .HasColumnType("int");

                b.Property<int?>("UbicacionAlmacenId")
                    .HasColumnType("int");

                b.Property<int>("UbicacionAlmacenIdUnica")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("int")
                    .HasComputedColumnSql("IFNULL(UbicacionAlmacenId, 0)", true);

                b.HasKey("Id");

                b.HasIndex("AlmacenId")
                    .HasDatabaseName("IX_ExistenciasVariante_AlmacenId");

                b.HasIndex("AlmacenId", "UbicacionAlmacenId");

                b.HasIndex("ProductoVarianteId", "AlmacenId")
                    .HasDatabaseName("IX_ExistenciasVariante_Variante_Almacen");

                b.HasIndex("ProductoVarianteId", "AlmacenId", "UbicacionAlmacenIdUnica")
                    .IsUnique()
                    .HasDatabaseName("UX_ExistenciasVariante_Variante_Almacen_Ubicacion");

                b.HasIndex("UbicacionAlmacenId")
                    .HasDatabaseName("IX_ExistenciasVariante_UbicacionAlmacenId");

                b.ToTable("ExistenciasVariante", (string)null);
            });
            modelBuilder.Entity("InventoryApp.Domain.Entities.Almacen", b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.Sucursal", "Sucursal")
                    .WithMany()
                    .HasForeignKey("SucursalId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_Almacenes_Sucursales_SucursalId");

                b.Navigation("Sucursal");
            });
            modelBuilder.Entity("InventoryApp.Domain.Entities.UbicacionAlmacen", b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.Almacen", "Almacen")
                    .WithMany()
                    .HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_UbicacionesAlmacen_Almacenes_AlmacenId");

                b.HasOne("InventoryApp.Domain.Entities.UbicacionAlmacen", "UbicacionPadre")
                    .WithMany("Hijas")
                    .HasForeignKey("AlmacenId", "UbicacionPadreId")
                    .HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_UbicacionesAlmacen_Padre_MismoAlmacen");

                b.Navigation("Almacen");

                b.Navigation("UbicacionPadre");
            });
            modelBuilder.Entity("InventoryApp.Domain.Entities.ExistenciaVariante", b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.Almacen", "Almacen")
                    .WithMany()
                    .HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_ExistenciasVariante_Almacenes_AlmacenId");

                b.HasOne("InventoryApp.Domain.Entities.ProductoVariante", "ProductoVariante")
                    .WithMany()
                    .HasForeignKey("ProductoVarianteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_ExistenciasVariante_ProductoVariantes_ProductoVarianteId");

                b.HasOne("InventoryApp.Domain.Entities.UbicacionAlmacen", "UbicacionAlmacen")
                    .WithMany()
                    .HasForeignKey("AlmacenId", "UbicacionAlmacenId")
                    .HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_ExistenciasVariante_Ubicacion_MismoAlmacen");

                b.Navigation("Almacen");
                b.Navigation("ProductoVariante");
                b.Navigation("UbicacionAlmacen");
            });
            modelBuilder.Entity("InventoryApp.Domain.Entities.Compra", b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.Catalogos.MetodoPago", "MetodoPagoCatalogo")
                    .WithMany()
                    .HasForeignKey("MetodoPagoId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_Compras_MetodosPago_MetodoPagoId");

                b.Navigation("MetodoPagoCatalogo");
            });
        }
    }
}
