// <auto-generated />
using InventoryApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InventoryApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            // Baseline canónico: último target model generado por EF antes del delta N0.5.11.
            // La próxima migración generada por EF volverá a expandir el snapshot normalmente.
            new ERP_N05_PermiteCambioAuditable().ApplyTargetModelForSnapshot(modelBuilder);

            modelBuilder.Entity("InventoryApp.Domain.Entities.Factura", b =>
            {
                b.Property<string>("MetodoPagoCodigoSnapshot")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<string>("MetodoPagoNombreSnapshot")
                    .HasMaxLength(120)
                    .HasColumnType("varchar(120)");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.FacturaPago", b =>
            {
                b.Property<string>("MetodoPagoCodigoSnapshot")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<string>("MetodoPagoNombreSnapshot")
                    .HasMaxLength(120)
                    .HasColumnType("varchar(120)");
            });
        }
    }

    public partial class ERP_N05_PermiteCambioAuditable
    {
        internal void ApplyTargetModelForSnapshot(ModelBuilder modelBuilder)
            => BuildTargetModel(modelBuilder);
    }
}
