// <auto-generated />
using InventoryApp.Domain.Entities;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryApp.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart23(ModelBuilder modelBuilder)
        {
            var cotizacion = modelBuilder.Entity<Cotizacion>();

            cotizacion.ToTable("Cotizaciones", table =>
            {
                table.HasCheckConstraint("CK_Cotizaciones_Estado_Valido", "`Estado` IN (0, 1, 2, 3, 4)");
            });

            cotizacion.Property(x => x.Id).ValueGeneratedOnAdd();
            cotizacion.Property(x => x.ClienteNombreSnapshot).HasMaxLength(200);
            cotizacion.Property(x => x.ClienteIdentidadSnapshot).HasMaxLength(50);
            cotizacion.Property(x => x.ClienteTelefonoSnapshot).HasMaxLength(30);
            cotizacion.Property(x => x.ClienteCorreoSnapshot).HasMaxLength(150);
            cotizacion.Property(x => x.Estado).HasConversion<int>();
            cotizacion.Property(x => x.Observaciones).HasMaxLength(1000);
            cotizacion.Property(x => x.CreadoPorNombreUsuario).HasMaxLength(150);
            cotizacion.Property(x => x.ActualizadoPorNombreUsuario).HasMaxLength(150);
            cotizacion.Ignore(x => x.Total);

            cotizacion.HasIndex(x => new { x.ClienteId, x.Estado, x.FechaEmisionUtc })
                .HasDatabaseName("IX_Cotizaciones_Cliente_Estado_FechaEmision");
            cotizacion.HasIndex(x => x.FechaVigenciaUtc)
                .HasDatabaseName("IX_Cotizaciones_FechaVigenciaUtc");

            cotizacion.HasOne(x => x.Cliente)
                .WithMany()
                .HasForeignKey(x => x.ClienteId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_Cotizaciones_Clientes_ClienteId");

            cotizacion.HasMany(x => x.Detalles)
                .WithOne(x => x.Cotizacion)
                .HasForeignKey(x => x.CotizacionId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CotizacionDetalles_Cotizaciones_CotizacionId");

            var detalle = modelBuilder.Entity<CotizacionDetalle>();

            detalle.ToTable("CotizacionDetalles", table =>
            {
                table.HasCheckConstraint("CK_CotizacionDetalles_Cantidad_Positiva", "`Cantidad` > 0");
                table.HasCheckConstraint("CK_CotizacionDetalles_PrecioUnitario_NoNegativo", "`PrecioUnitario` >= 0");
            });

            detalle.Property(x => x.Id).ValueGeneratedOnAdd();
            detalle.Property(x => x.ProductoSkuSnapshot).HasMaxLength(80);
            detalle.Property(x => x.ProductoNombreSnapshot).HasMaxLength(150);
            detalle.Property(x => x.ProductoMarcaSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoModeloSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoColorSnapshot).HasMaxLength(100);
            detalle.Property(x => x.ProductoTallaSnapshot).HasMaxLength(100);
            detalle.Property(x => x.Cantidad).HasPrecision(18, 4);
            detalle.Property(x => x.PrecioUnitario).HasPrecision(18, 4);
            detalle.Property(x => x.CreadoPorNombreUsuario).HasMaxLength(150);
            detalle.Property(x => x.ActualizadoPorNombreUsuario).HasMaxLength(150);
            detalle.Ignore(x => x.Total);

            detalle.HasIndex(x => new { x.CotizacionId, x.ProductoId, x.ProductoVarianteId })
                .HasDatabaseName("IX_CotizacionDetalles_Cotizacion_Producto_Variante");
            detalle.HasIndex(x => x.ProductoId)
                .HasDatabaseName("IX_CotizacionDetalles_ProductoId");
            detalle.HasIndex(x => x.ProductoVarianteId)
                .HasDatabaseName("IX_CotizacionDetalles_ProductoVarianteId");

            detalle.HasOne(x => x.Producto)
                .WithMany()
                .HasForeignKey(x => x.ProductoId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_CotizacionDetalles_Productos_ProductoId");
            detalle.HasOne(x => x.ProductoVariante)
                .WithMany()
                .HasForeignKey(x => x.ProductoVarianteId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_CotizacionDetalles_ProductoVariantes_ProductoVarianteId");
        }
    }
}
