// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace InventoryApp.Infrastructure.Migrations
{
    internal static partial class AppDbContextSnapshotN14D
    {
        private static void ApplyPart13(ModelBuilder modelBuilder)
        {
            // Normalización de anotación heredada del charset global MySQL para N1.10.
            modelBuilder.Entity("InventoryApp.Domain.Entities.PoliticaCosteoInventario", b => b.HasCharSet("utf8mb4"));
            modelBuilder.Entity("InventoryApp.Domain.Entities.CostoEstandarInventario", b => b.HasCharSet("utf8mb4"));
            modelBuilder.Entity("InventoryApp.Domain.Entities.CapaCostoInventario", b => b.HasCharSet("utf8mb4"));
            modelBuilder.Entity("InventoryApp.Domain.Entities.AsignacionCostoMovimientoInventario", b => b.HasCharSet("utf8mb4"));
            modelBuilder.Entity("InventoryApp.Domain.Entities.VariacionCostoEstandarInventario", b => b.HasCharSet("utf8mb4"));
        }
    }
}
