// <auto-generated />
using InventoryApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InventoryApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
            => AppDbContextSnapshotN14D.Apply(modelBuilder);
    }

    internal static partial class AppDbContextSnapshotN14D
    {
        internal static void Apply(ModelBuilder modelBuilder)
        {
            ApplyPart1(modelBuilder); ApplyPart2(modelBuilder); ApplyPart3(modelBuilder); ApplyPart4(modelBuilder); ApplyPart5(modelBuilder);
            ApplyPart6(modelBuilder); ApplyPart7(modelBuilder); ApplyPart8(modelBuilder); ApplyPart9(modelBuilder); ApplyPart10(modelBuilder);
            ApplyPart11(modelBuilder); ApplyPart12(modelBuilder); ApplyPart13(modelBuilder); ApplyPart14(modelBuilder); ApplyPart15(modelBuilder);
            ApplyPart16(modelBuilder); ApplyPart17(modelBuilder); ApplyPart18(modelBuilder); ApplyPart19(modelBuilder); ApplyPart20(modelBuilder);
            ApplyPart21(modelBuilder); ApplyPart22(modelBuilder); ApplyPart23(modelBuilder); ApplyPart24(modelBuilder); ApplyPart25(modelBuilder);
            ApplyPart26(modelBuilder); ApplyPart27(modelBuilder); ApplyPart28(modelBuilder); ApplyPart29(modelBuilder);
        }
    }

    public partial class ERP_N05_PermiteCambioAuditable
    {
        internal void ApplyTargetModelForSnapshot(ModelBuilder modelBuilder)
        {
            // Preserve the generated N0.5 baseline exactly as emitted. Its historical
            // string-based entities must not be pre-bound to newer CLR types because
            // legacy property names/types (for example Venta.Estado) do not necessarily
            // match the current CLR member shape. Later snapshot parts reconcile new
            // relationships explicitly without mutating this historical baseline.
            BuildTargetModel(modelBuilder);
        }
    }
}
