// <auto-generated />
using System;
using InventoryApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InventoryApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            // Baseline canónico: último target model generado por EF antes del delta N0.5.11.
            // Los deltas posteriores se mantienen explícitos para preservar has-pending-model-changes.
            new ERP_N05_PermiteCambioAuditable().ApplyTargetModelForSnapshot(modelBuilder);

            modelBuilder.Entity("InventoryApp.Domain.Entities.Factura", b =>
            {
                b.Property<string>("MetodoPagoCodigoSnapshot")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<string>("MetodoPagoNombreSnapshot")
                    .HasMaxLength(120)
                    .HasColumnType("varchar(120)");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.FacturaPago", b =>
            {
                b.Property<string>("MetodoPagoCodigoSnapshot")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<string>("MetodoPagoNombreSnapshot")
                    .HasMaxLength(120)
                    .HasColumnType("varchar(120)");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.Compra", b =>
            {
                b.Property<int?>("MetodoPagoId")
                    .HasColumnType("int");

                b.HasIndex("MetodoPagoId")
                    .HasDatabaseName("IX_Compras_MetodoPagoId");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.MovimientoInventario", b =>
            {
                b.Property<int?>("CompraId")
                    .HasColumnType("int");

                b.Property<int?>("VentaId")
                    .HasColumnType("int");

                b.Property<int?>("ConsumoInsumoId")
                    .HasColumnType("int");

                b.Property<int?>("AjusteInventarioId")
                    .HasColumnType("int");

                b.HasIndex("CompraId")
                    .HasDatabaseName("IX_MovimientosInventario_CompraId");

                b.HasIndex("VentaId")
                    .HasDatabaseName("IX_MovimientosInventario_VentaId");

                b.HasIndex("ConsumoInsumoId")
                    .HasDatabaseName("IX_MovimientosInventario_ConsumoInsumoId");

                b.HasIndex("AjusteInventarioId")
                    .HasDatabaseName("IX_MovimientosInventario_AjusteInventarioId");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.AjusteInventario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("AnuladoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("AnuladoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("ConfirmadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ConfirmadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("FechaAnulacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaAjuste")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("FechaConfirmacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Motivo")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<string>("MotivoAnulacion")
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<string>("NumeroAjuste")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)");

                b.Property<string>("Observaciones")
                    .HasMaxLength(1000)
                    .HasColumnType("varchar(1000)");

                b.HasKey("Id");

                b.HasIndex("Estado", "FechaAjuste")
                    .HasDatabaseName("IX_AjustesInventario_Estado_Fecha");

                b.HasIndex("NumeroAjuste")
                    .IsUnique()
                    .HasDatabaseName("UX_AjustesInventario_Numero");

                b.ToTable("AjustesInventario", (string)null);
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.AjusteInventarioDetalle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("AjusteInventarioId")
                    .HasColumnType("int");

                b.Property<int?>("CantidadAnteriorSnapshot")
                    .HasColumnType("int");

                b.Property<int?>("CantidadNuevaSnapshot")
                    .HasColumnType("int");

                b.Property<int>("CantidadObjetivo")
                    .HasColumnType("int");

                b.Property<string>("ColorSnapshot")
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<decimal?>("CostoUnitarioSnapshot")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("MarcaSnapshot")
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("ModeloSnapshot")
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("NombreSnapshot")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int>("ProductoId")
                    .HasColumnType("int");

                b.Property<int?>("ProductoVarianteId")
                    .HasColumnType("int");

                b.Property<string>("SkuSnapshot")
                    .HasMaxLength(80)
                    .HasColumnType("varchar(80)");

                b.Property<string>("TallaSnapshot")
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.HasKey("Id");

                b.HasIndex("AjusteInventarioId")
                    .HasDatabaseName("IX_AjusteInventarioDetalles_AjusteInventarioId");

                b.HasIndex("ProductoId", "ProductoVarianteId")
                    .HasDatabaseName("IX_AjusteInventarioDetalles_Producto_Variante");

                b.HasIndex("ProductoVarianteId");

                b.ToTable("AjusteInventarioDetalles", (string)null);
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.Sucursal", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<bool>("Activa")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true);

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("varchar(40)");

                b.Property<string>("CodigoActivoUnico")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasMaxLength(40)
                    .HasColumnType("varchar(40)")
                    .HasComputedColumnSql("IF(Eliminado = 0, UPPER(TRIM(Codigo)), NULL)", true);

                b.Property<string>("Correo")
                    .HasMaxLength(254)
                    .HasColumnType("varchar(254)");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("Direccion")
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<bool>("Eliminado")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(false);

                b.Property<int?>("EliminadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<int?>("EmpresaId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("FechaEliminacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<string>("Telefono")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<string>("ZonaHoraria")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)")
                    .HasDefaultValue("America/Tegucigalpa");

                b.HasKey("Id");

                b.HasIndex("CodigoActivoUnico")
                    .IsUnique()
                    .HasDatabaseName("UX_Sucursales_Codigo_Activo");

                b.HasIndex("EmpresaId")
                    .HasDatabaseName("IX_Sucursales_EmpresaId");

                b.HasIndex("Activa", "Eliminado")
                    .HasDatabaseName("IX_Sucursales_Estado");

                b.ToTable("Sucursales", (string)null);
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.Almacen", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Activo")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true);

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("varchar(40)");

                b.Property<string>("CodigoActivoUnico")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasMaxLength(40)
                    .HasColumnType("varchar(40)")
                    .HasComputedColumnSql("IF(Eliminado = 0, UPPER(TRIM(Codigo)), NULL)", true);

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<bool>("Eliminado")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(false);

                b.Property<int?>("EliminadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("FechaEliminacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int>("SucursalId")
                    .HasColumnType("int");

                b.Property<int>("Tipo")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CodigoActivoUnico")
                    .IsUnique()
                    .HasDatabaseName("UX_Almacenes_Codigo_Activo");

                b.HasIndex("SucursalId")
                    .HasDatabaseName("IX_Almacenes_SucursalId");

                b.HasIndex("Tipo", "Activo", "Eliminado")
                    .HasDatabaseName("IX_Almacenes_Tipo_Estado");

                b.ToTable("Almacenes", (string)null);
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.UbicacionAlmacen", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Activa")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true);

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<int>("AlmacenId")
                    .HasColumnType("int");

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(60)
                    .HasColumnType("varchar(60)");

                b.Property<string>("CodigoActivoUnico")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasMaxLength(60)
                    .HasColumnType("varchar(60)")
                    .HasComputedColumnSql("IF(Eliminado = 0, UPPER(TRIM(Codigo)), NULL)", true);

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<bool>("Eliminado")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(false);

                b.Property<int?>("EliminadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("FechaEliminacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int>("Tipo")
                    .HasColumnType("int");

                b.Property<int?>("UbicacionPadreId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasAlternateKey("AlmacenId", "Id")
                    .HasName("AK_UbicacionesAlmacen_AlmacenId_Id");

                b.HasIndex("AlmacenId")
                    .HasDatabaseName("IX_UbicacionesAlmacen_AlmacenId");

                b.HasIndex("AlmacenId", "CodigoActivoUnico")
                    .IsUnique()
                    .HasDatabaseName("UX_UbicacionesAlmacen_Almacen_Codigo_Activo");

                b.HasIndex("AlmacenId", "UbicacionPadreId")
                    .HasDatabaseName("IX_UbicacionesAlmacen_Padre");

                b.HasIndex("Tipo", "Activa", "Eliminado")
                    .HasDatabaseName("IX_UbicacionesAlmacen_Tipo_Estado");

                b.ToTable("UbicacionesAlmacen", (string)null);
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.ExistenciaVariante", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<int>("AlmacenId")
                    .HasColumnType("int");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<int>("ProductoVarianteId")
                    .HasColumnType("int");

                b.Property<int>("StockDisponible")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("int")
                    .HasComputedColumnSql("StockFisico - StockReservado", true);

                b.Property<int>("StockFisico")
                    .HasColumnType("int");

                b.Property<int?>("StockMaximo")
                    .HasColumnType("int");

                b.Property<int>("StockMinimo")
                    .HasColumnType("int");

                b.Property<int>("StockReservado")
                    .HasColumnType("int");

                b.Property<int>("StockTransito")
                    .HasColumnType("int");

                b.Property<int?>("UbicacionAlmacenId")
                    .HasColumnType("int");

                b.Property<int>("UbicacionAlmacenIdUnica")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("int")
                    .HasComputedColumnSql("IFNULL(UbicacionAlmacenId, 0)", true);

                b.HasKey("Id");

                b.HasIndex("AlmacenId")
                    .HasDatabaseName("IX_ExistenciasVariante_AlmacenId");

                b.HasIndex("AlmacenId", "UbicacionAlmacenId");

                b.HasIndex("ProductoVarianteId", "AlmacenId")
                    .HasDatabaseName("IX_ExistenciasVariante_Variante_Almacen");

                b.HasIndex("ProductoVarianteId", "AlmacenId", "UbicacionAlmacenIdUnica")
                    .IsUnique()
                    .HasDatabaseName("UX_ExistenciasVariante_Variante_Almacen_Ubicacion");

                b.HasIndex("UbicacionAlmacenId")
                    .HasDatabaseName("IX_ExistenciasVariante_UbicacionAlmacenId");

                b.ToTable("ExistenciasVariante", (string)null);
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.Almacen", b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.Sucursal", "Sucursal")
                    .WithMany()
                    .HasForeignKey("SucursalId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_Almacenes_Sucursales_SucursalId");

                b.Navigation("Sucursal");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.UbicacionAlmacen", b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.Almacen", "Almacen")
                    .WithMany()
                    .HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_UbicacionesAlmacen_Almacenes_AlmacenId");

                b.HasOne("InventoryApp.Domain.Entities.UbicacionAlmacen", "UbicacionPadre")
                    .WithMany("Hijas")
                    .HasForeignKey("AlmacenId", "UbicacionPadreId")
                    .HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_UbicacionesAlmacen_Padre_MismoAlmacen");

                b.Navigation("Almacen");

                b.Navigation("UbicacionPadre");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.ExistenciaVariante", b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.Almacen", "Almacen")
                    .WithMany()
                    .HasForeignKey("AlmacenId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_ExistenciasVariante_Almacenes_AlmacenId");

                b.HasOne("InventoryApp.Domain.Entities.ProductoVariante", "ProductoVariante")
                    .WithMany()
                    .HasForeignKey("ProductoVarianteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_ExistenciasVariante_ProductoVariantes_ProductoVarianteId");

                b.HasOne("InventoryApp.Domain.Entities.UbicacionAlmacen", "UbicacionAlmacen")
                    .WithMany()
                    .HasForeignKey("AlmacenId", "UbicacionAlmacenId")
                    .HasPrincipalKey("AlmacenId", "Id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_ExistenciasVariante_Ubicacion_MismoAlmacen");

                b.Navigation("Almacen");
                b.Navigation("ProductoVariante");
                b.Navigation("UbicacionAlmacen");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.Compra", b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.Catalogos.MetodoPago", "MetodoPagoCatalogo")
                    .WithMany()
                    .HasForeignKey("MetodoPagoId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_Compras_MetodosPago_MetodoPagoId");

                b.Navigation("MetodoPagoCatalogo");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.MovimientoInventario", b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.Compra", null)
                    .WithMany()
                    .HasForeignKey("CompraId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovimientosInventario_Compras_CompraId_N06");

                b.HasOne("InventoryApp.Domain.Entities.Venta", null)
                    .WithMany()
                    .HasForeignKey("VentaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovimientosInventario_Ventas_VentaId_N06");

                b.HasOne("InventoryApp.Domain.Entities.ConsumoInsumo", null)
                    .WithMany()
                    .HasForeignKey("ConsumoInsumoId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovimientosInventario_ConsumosInsumos_ConsumoInsumoId_N06");

                b.HasOne("InventoryApp.Domain.Entities.AjusteInventario", null)
                    .WithMany()
                    .HasForeignKey("AjusteInventarioId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_MovInv_AjusteInventarioId_N07");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.AjusteInventarioDetalle", b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.AjusteInventario", "AjusteInventario")
                    .WithMany("Detalles")
                    .HasForeignKey("AjusteInventarioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_AjusteInventarioDetalles_AjustesInventario");

                b.HasOne("InventoryApp.Domain.Entities.Producto", "Producto")
                    .WithMany()
                    .HasForeignKey("ProductoId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_AjusteInventarioDetalles_Productos");

                b.HasOne("InventoryApp.Domain.Entities.ProductoVariante", "ProductoVariante")
                    .WithMany()
                    .HasForeignKey("ProductoVarianteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_AjusteInventarioDetalles_ProductoVariantes");

                b.Navigation("AjusteInventario");
                b.Navigation("Producto");
                b.Navigation("ProductoVariante");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.AjusteInventario", b =>
            {
                b.Navigation("Detalles");
            });
            modelBuilder.Entity("InventoryApp.Domain.Entities.UbicacionAlmacen", b =>
            {
                b.Navigation("Hijas");
            });
        }
    }

    public partial class ERP_N05_PermiteCambioAuditable
    {
        internal void ApplyTargetModelForSnapshot(ModelBuilder modelBuilder)
            => BuildTargetModel(modelBuilder);
    }
}
