// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace InventoryApp.Infrastructure.Migrations
{
    partial class AppDbContextModelSnapshot
    {
        /// <summary>
        /// N6.9.C — overlay de snapshot para Plan, PlanLimite y Suscripcion.
        /// Conserva el snapshot canonico historico y deja verificable el modelo
        /// relacional introducido por 20260912214800_N69CSuscripcionesSaaSPersistence.
        /// </summary>
        private static void ApplyN69CModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.Entity("InventoryApp.Domain.Entities.Plan", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Activo")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true);

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("varchar(80)");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)");

                b.HasKey("Id");

                b.HasIndex("Codigo")
                    .IsUnique()
                    .HasDatabaseName("UX_Planes_Codigo");

                b.ToTable("Planes", (string)null);
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.Suscripcion", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActualizadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("ActualizadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<string>("CreadoPorNombreUsuario")
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<int?>("CreadoPorUsuarioId")
                    .HasColumnType("int");

                b.Property<int>("EmpresaId")
                    .HasColumnType("int");

                b.Property<int>("Estado")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("FinUtc")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("InicioUtc")
                    .HasColumnType("datetime(6)");

                b.Property<int>("PlanId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("EmpresaId", "Estado")
                    .HasDatabaseName("IX_Suscripciones_EmpresaId_Estado");

                b.HasIndex("EmpresaId", "InicioUtc")
                    .HasDatabaseName("IX_Suscripciones_EmpresaId_InicioUtc");

                b.HasIndex("PlanId", "Estado")
                    .HasDatabaseName("IX_Suscripciones_PlanId_Estado");

                b.ToTable("Suscripciones", (string)null);
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.Plan", b =>
            {
                b.OwnsMany("InventoryApp.Domain.Entities.PlanLimite", "Limites", b1 =>
                {
                    b1.Property<int>("PlanId")
                        .HasColumnType("int");

                    b1.Property<string>("Clave")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b1.Property<int?>("ValorMaximo")
                        .HasColumnType("int");

                    b1.HasKey("PlanId", "Clave");

                    b1.HasIndex("PlanId")
                        .HasDatabaseName("IX_PlanLimites_PlanId");

                    b1.ToTable("PlanLimites", (string)null);

                    b1.WithOwner()
                        .HasForeignKey("PlanId");
                });

                b.Navigation("Limites");
            });

            modelBuilder.Entity("InventoryApp.Domain.Entities.Suscripcion", b =>
            {
                b.HasOne("InventoryApp.Domain.Entities.Empresa", null)
                    .WithMany()
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("InventoryApp.Domain.Entities.Plan", null)
                    .WithMany()
                    .HasForeignKey("PlanId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
