export interface MovimientoInventario {
  id: number;
  productoId: number;
  productoVarianteId?: number | null;
  almacenId?: number | null;
  ubicacionAlmacenId?: number | null;
  productoNombre: string;
  productoColor?: string | null;
  productoSku?: string | null;
  productoImagenPrincipalUrl?: string | null;
  tipo: 'Entrada' | 'Salida' | 'Ajuste' | 'Reversion';
  causa: string;
  cantidad: number;
  stockAnterior: number;
  stockNuevo: number;
  costoUnitario?: number | null;
  precioUnitario?: number | null;
  correlationId: string;
  origenTipo?: string | null;
  origenId?: number | null;
  compraId?: number | null;
  ventaId?: number | null;
  consumoInsumoId?: number | null;
  ajusteInventarioId?: number | null;
  referenciaTipo: string;
  referenciaId: number;
  descripcion?: string | null;
  creadoPorNombreUsuario?: string | null;
  fecha: string;
}
