import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { PermisosRuntimeService } from '../../core/auth/permisos-runtime.service';
import { EstadoPedidoVenta, PedidoVenta } from './pedido-venta.model';
import { PedidoVentaService } from './pedido-venta.service';

const UI=[CommonModule,RouterLink,MatButtonModule,MatCardModule,MatFormFieldModule,MatIconModule,MatInputModule,MatSelectModule,MatSnackBarModule,MatProgressSpinnerModule];
const estado=(e:EstadoPedidoVenta)=>EstadoPedidoVenta[e]??String(e);

@Component({selector:'app-pedidos-venta-list',standalone:true,imports:UI,template:`<section class="page"><header><div><h1>Pedidos de venta</h1><p>Seguimiento de pedidos originados desde cotizaciones aceptadas.</p></div>@if(puede('Crear')){<a mat-flat-button color="primary" routerLink="/pedidos-venta/nuevo"><mat-icon>add</mat-icon>Nuevo pedido</a>}</header><mat-card><mat-card-content><mat-form-field appearance="outline"><mat-label>Estado</mat-label><mat-select [value]="filtroEstado" (selectionChange)="filtrar($event.value)"><mat-option [value]="null">Todos</mat-option>@for(e of estados;track e){<mat-option [value]="e">{{nombre(e)}}</mat-option>}</mat-select></mat-form-field>@if(loading()){<div class="center" role="status"><mat-spinner diameter="40"/></div>}@else if(error()){<div class="center" role="alert">No fue posible cargar los pedidos. <button mat-button (click)="cargar()">Reintentar</button></div>}@else{<div class="table"><table><thead><tr><th>ID</th><th>Cotización</th><th>Cliente</th><th>Estado</th><th>Total</th><th><span class="sr">Acciones</span></th></tr></thead><tbody>@for(p of items();track p.id){<tr><td>PED-{{p.id}}</td><td>{{p.cotizacionId?('COT-'+p.cotizacionId):'—'}}</td><td>{{p.clienteNombreSnapshot}}</td><td>{{nombre(p.estado)}}</td><td>{{p.total|number:'1.2-2'}}</td><td><a mat-icon-button [routerLink]="['/pedidos-venta',p.id]" aria-label="Ver pedido"><mat-icon>visibility</mat-icon></a>@if(p.estado===EstadoPedidoVenta.Borrador&&puede('Editar')){<a mat-icon-button [routerLink]="['/pedidos-venta',p.id,'editar']" aria-label="Editar pedido"><mat-icon>edit</mat-icon></a>}</td></tr>}@empty{<tr><td colspan="6">Sin resultados.</td></tr>}</tbody></table></div><footer><span>{{total()}} registro(s)</span><div><button mat-button [disabled]="page<=1" (click)="pagina(page-1)">Anterior</button><span>Página {{page}}</span><button mat-button [disabled]="page*pageSize>=total()" (click)="pagina(page+1)">Siguiente</button></div></footer>}</mat-card-content></mat-card></section>`,styles:[`.page{max-width:1200px;margin:auto;padding:16px}header,footer{display:flex;justify-content:space-between;gap:16px;align-items:center}header{margin-bottom:16px}h1{margin:0}.center{text-align:center;padding:36px}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;text-align:left;border-bottom:1px solid var(--color-border)}footer{padding-top:12px}footer div{display:flex;gap:8px;align-items:center}.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:700px){header,footer{align-items:flex-start;flex-direction:column}}`]})
export class PedidosVentaListComponent implements OnInit{private svc=inject(PedidoVentaService);private permisos=inject(PermisosRuntimeService);readonly items=signal<PedidoVenta[]>([]);readonly total=signal(0);readonly loading=signal(false);readonly error=signal(false);readonly EstadoPedidoVenta=EstadoPedidoVenta;readonly estados=[1,2,3] as EstadoPedidoVenta[];page=1;pageSize=10;filtroEstado:EstadoPedidoVenta|null=null;ngOnInit(){this.cargar()}puede(a:string){return this.permisos.puede('Ventas',a)}nombre(e:EstadoPedidoVenta){return estado(e)}filtrar(e:EstadoPedidoVenta|null){this.filtroEstado=e;this.page=1;this.cargar()}pagina(p:number){this.page=Math.max(1,p);this.cargar()}cargar(){this.loading.set(true);this.error.set(false);this.svc.getPaged({page:this.page,pageSize:this.pageSize,estado:this.filtroEstado,sortBy:'Id',sortDirection:'desc'}).subscribe({next:r=>{this.items.set(r.data.items);this.total.set(r.data.totalCount);this.loading.set(false)},error:()=>{this.error.set(true);this.loading.set(false)}})}}

@Component({selector:'app-pedido-venta-form',standalone:true,imports:[...UI,ReactiveFormsModule],template:`<section class="page"><header><h1>{{editando?'Editar':'Nuevo'}} pedido de venta</h1><a mat-stroked-button routerLink="/pedidos-venta">Cancelar</a></header>@if(loading()){<div class="center" role="status"><mat-spinner diameter="40"/></div>}@else{<form [formGroup]="form" (ngSubmit)="guardar()"><mat-card><mat-card-content class="grid"><mat-form-field appearance="outline"><mat-label>ID de cotización aceptada</mat-label><input matInput type="number" min="1" formControlName="cotizacionId" [readonly]="editando"><mat-hint>El pedido se crea exclusivamente desde una cotización aceptada.</mat-hint></mat-form-field><mat-form-field appearance="outline"><mat-label>Observaciones</mat-label><textarea matInput formControlName="observaciones" rows="5"></textarea></mat-form-field></mat-card-content></mat-card><div class="actions"><button mat-flat-button color="primary" type="submit" [disabled]="saving()">Guardar</button></div></form>}</section>`,styles:[`.page{max-width:900px;margin:auto;padding:16px}header,.actions{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:16px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.center{text-align:center;padding:36px}@media(max-width:700px){header,.grid{grid-template-columns:1fr;align-items:flex-start;flex-direction:column}}`]})
export class PedidoVentaFormComponent implements OnInit{private fb=inject(FormBuilder);private svc=inject(PedidoVentaService);private route=inject(ActivatedRoute);private router=inject(Router);private snack=inject(MatSnackBar);readonly loading=signal(false);readonly saving=signal(false);editando=false;id?:number;private createKey=globalThis.crypto?.randomUUID?.()??`pedido-${Date.now()}-${Math.random().toString(16).slice(2)}`;readonly form=this.fb.group({cotizacionId:[null as number|null,Validators.required],observaciones:['']});ngOnInit(){const cotizacionId=Number(this.route.snapshot.queryParamMap.get('cotizacionId'));if(Number.isInteger(cotizacionId)&&cotizacionId>0)this.form.patchValue({cotizacionId});const id=Number(this.route.snapshot.paramMap.get('id'));if(Number.isInteger(id)&&id>0){this.editando=true;this.id=id;this.cargar(id)}}private cargar(id:number){this.loading.set(true);this.svc.getById(id).subscribe({next:r=>{const p=r.data;if(p.estado!==EstadoPedidoVenta.Borrador){void this.router.navigate(['/pedidos-venta',id]);return}this.form.patchValue({cotizacionId:p.cotizacionId??null,observaciones:p.observaciones??''});this.loading.set(false)},error:()=>{this.loading.set(false);this.snack.open('No fue posible cargar el pedido.','Cerrar',{duration:4000})}})}guardar(){if(this.form.invalid){this.form.markAllAsTouched();return}const v=this.form.getRawValue();this.saving.set(true);const q=this.editando&&this.id?this.svc.update(this.id,{id:this.id,observaciones:v.observaciones?.trim()||null}):this.svc.create({cotizacionId:Number(v.cotizacionId),observaciones:v.observaciones?.trim()||null},this.createKey);q.subscribe({next:r=>{this.saving.set(false);void this.router.navigate(['/pedidos-venta',r.data.id])},error:e=>{this.saving.set(false);this.snack.open(e.error?.detail||e.error?.message||'No fue posible guardar el pedido.','Cerrar',{duration:5000})}})}}

@Component({selector:'app-pedido-venta-detail',standalone:true,imports:UI,template:`<section class="page">@if(loading()){<div class="center" role="status"><mat-spinner diameter="40"/></div>}@else if(pedido();as p){<header><div><h1>Pedido PED-{{p.id}}</h1><p>{{p.clienteNombreSnapshot}} · {{nombre(p.estado)}}</p></div><a mat-stroked-button routerLink="/pedidos-venta">Volver</a></header><div class="actions">@if(p.estado===EstadoPedidoVenta.Borrador&&puede('Editar')){<a mat-stroked-button [routerLink]="['/pedidos-venta',p.id,'editar']">Editar</a>}@if(p.estado===EstadoPedidoVenta.Borrador&&puede('Confirmar')){<button mat-flat-button color="primary" (click)="confirmar()">Confirmar</button>}@if(p.estado===EstadoPedidoVenta.Confirmado&&puede('Anular')){<button mat-stroked-button color="warn" (click)="anular()">Anular</button>}</div><mat-card><mat-card-content><p><strong>Cotización:</strong> {{p.cotizacionId?('COT-'+p.cotizacionId):'—'}}</p><p><strong>Cliente:</strong> {{p.clienteNombreSnapshot}}</p><p><strong>Documento:</strong> {{p.clienteDocumentoSnapshot||'—'}}</p><p><strong>Total:</strong> {{p.total|number:'1.2-2'}}</p>@if(p.observaciones){<p><strong>Observaciones:</strong> {{p.observaciones}}</p>}@if(p.motivoAnulacion){<p><strong>Motivo anulación:</strong> {{p.motivoAnulacion}}</p>}<div class="table"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio</th><th>Total</th></tr></thead><tbody>@for(d of p.detalles;track d.id){<tr><td>{{d.productoNombreSnapshot||('Producto #'+d.productoId)}}</td><td>{{d.cantidad|number:'1.0-4'}}</td><td>{{d.precioUnitario|number:'1.2-4'}}</td><td>{{d.total|number:'1.2-4'}}</td></tr>}@empty{<tr><td colspan="4">Sin detalles.</td></tr>}</tbody></table></div></mat-card-content></mat-card>}</section>`,styles:[`.page{max-width:1100px;margin:auto;padding:16px}header,.actions{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:16px}.actions{justify-content:flex-start;flex-wrap:wrap}.center{text-align:center;padding:36px}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:10px;text-align:left;border-bottom:1px solid var(--color-border)}@media(max-width:700px){header{align-items:flex-start;flex-direction:column}}`]})
export class PedidoVentaDetailComponent implements OnInit{private svc=inject(PedidoVentaService);private permisos=inject(PermisosRuntimeService);private route=inject(ActivatedRoute);private router=inject(Router);private snack=inject(MatSnackBar);readonly pedido=signal<PedidoVenta|null>(null);readonly loading=signal(true);readonly EstadoPedidoVenta=EstadoPedidoVenta;ngOnInit(){const id=Number(this.route.snapshot.paramMap.get('id'));if(!Number.isInteger(id)||id<=0){void this.router.navigate(['/pedidos-venta']);return}this.cargar(id)}puede(a:string){return this.permisos.puede('Ventas',a)}nombre(e:EstadoPedidoVenta){return estado(e)}private cargar(id:number){this.loading.set(true);this.svc.getById(id).subscribe({next:r=>{this.pedido.set(r.data);this.loading.set(false)},error:()=>{this.loading.set(false);this.snack.open('No fue posible cargar el pedido.','Cerrar',{duration:4000})}})}confirmar(){const p=this.pedido();if(!p||!confirm('¿Confirmar este pedido de venta?'))return;this.svc.confirmar(p.id).subscribe({next:r=>this.pedido.set(r.data),error:e=>this.snack.open(e.error?.detail||e.error?.message||'No fue posible confirmar.','Cerrar',{duration:5000})})}anular(){const p=this.pedido();if(!p)return;const motivo=prompt('Motivo de anulación');if(!motivo?.trim())return;this.svc.anular(p.id,motivo).subscribe({next:r=>this.pedido.set(r.data),error:e=>this.snack.open(e.error?.detail||e.error?.message||'No fue posible anular.','Cerrar',{duration:5000})})}}
